GET http://localhost:5000/getUsers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1vY2hydWxseUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6Ik1vY2hhbWFkIFJ1bGx5IFByYXNldHlvIiwicGFzc3dvcmQiOiJNb2NoYW1hZCBSdWxseSBQcmFzZXR5byIsImlkX2xldmVsIjoxLCJpYXQiOjE3MTExNTAyOTQsImV4cCI6MTcxMTE1MTE5NH0.izfTxCY7P728rK8jBr0DWS8HIYPzp9bk7kQZGawmou8

###
GET http://localhost:5000/getUserbyId/31
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkcmllbCBPbWFycGFkdSBQYW5kaWFuZ2FuIiwicGFzc3dvcmQiOiJBZHJpZWwgT21hcnBhZHUgUGFuZGlhbmdhbiIsImlkX2xldmVsIjo2LCJpYXQiOjE3MDg4MDUyMjQsImV4cCI6MTcwODgwNjEyNH0.54L0XkuEGJGQsop1o1_4mJ_D6XZDxntSaL-WM_o5rtU

###
GET http://localhost:5000/getUsersbyPartialUsername/Deni
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1vY2hydWxseUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6Ik1vY2hhbWFkIFJ1bGx5IFByYXNldHlvIiwicGFzc3dvcmQiOiJNb2NoYW1hZCBSdWxseSBQcmFzZXR5byIsImlkX2xldmVsIjoxLCJpYXQiOjE3MTExMjc1MDQsImV4cCI6MTcxMTEyODQwNH0.fg498jq3mNfhBhdIgupdZwuBABVUd6LFlNCrJuB7z_I

###
GET http://localhost:5000/getUsersbyProdi/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1vY2hhbWFkIFJ1bGx5IFByYXNldHlvIiwicGFzc3dvcmQiOiJNb2NoYW1hZCBSdWxseSBQcmFzZXR5byIsImlkX2xldmVsIjoxLCJpYXQiOjE3MDgxNzkwMzQsImV4cCI6MTcwODE3OTkzNH0.o6rwtSRpesNrmtL-rJzdopEja-_N-8STtcDm7rcGBXQ

###
GET http://localhost:5000/getApprovedIjinSakit/82

###
PATCH http://localhost:5000/editUser/15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkcmllbCBPbWFycGFkdSBQYW5kaWFuZ2FuIiwicGFzc3dvcmQiOiJBZHJpZWwgT21hcnBhZHUgUGFuZGlhbmdhbiIsImlkX2xldmVsIjo2LCJpYXQiOjE3MDc4MzExNDIsImV4cCI6MTcwNzgzMjA0Mn0.6ewzBrQlNJag1Lmf8km5JP1UXDHPhU_nqHnaoqQyfNs
Content-Type: application/json

{
    "username" : "Gutri Rahmad Zuwa",
    "password" : "Gutri Rahmad Zuwa"
}

###
GET http://localhost:5000/refreshToken

###
GET http://localhost:5000/getijinbyidketijin/1

###
PATCH http://localhost:5000/deleteijin/71

###
PATCH http://localhost:5000/approvedIjinSakit/82


###
DELETE http://localhost:5000/deleteUser/6

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "Adriel Omarpadu Pandiangan",
    "password": "Adriel Omarpadu Pandiangan"
}

### Login Admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "mochrully@gmail.com",
    "password": "Mochamad Rully Prasetyo"
}


###
POST http://localhost:5000/register

Content-Type: application/json

{
    "username": "Adriel Omarpadu Pandiangan",
    "password": "Adriel Omarpadu Pandiangan",
    "email": "dielp632@gmail.com",
    "no_personel": "320200401001",
    "id_level": "6"
}


###
GET http://localhost:5000/refreshToken

###
DELETE http://localhost:5000/logout

###
GET http://localhost:5000/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1vY2hhbWFkIFJ1bGx5IFByYXNldHlvIiwiZW1haWwiOiJtb2NocnVsbHlAZ21haWwuY29tIiwiaWRfbGV2ZWwiOjEsImlhdCI6MTcwODYwNjYxOCwiZXhwIjoxNzA4NjA3NTE4fQ.d5UWfTjvn73bszACBmVqdMpJhzFN4YdpUrYjsrpby8s

###
POST http://localhost:5000/sicknessPermit/31
Content-Type: multipart/form-data

{
    "id_ketijin": 1,
    "tanggal_mulai": "2024-02-25",
    "tanggal_selesai": "2024-02-26",
    "files": "file",
    "deskripsi": "Sakit perut",
    "id_status": 1
}


###
GET http://localhost:5000/getProdi

###
GET http://localhost:5000/getFakultas

###
GET http://localhost:5000/pengajuanIzin/2

###
GET http://localhost:5000/ketijin

###
GET http://localhost:5000/listPengajuanIzin

###
DELETE http://localhost:5000/hapusPengajuanIzin/90

###
GET http://localhost:5000/getLevel

###
GET http://localhost:5000/getKetangkatan

###
GET http://localhost:5000/getUserbyProdiandAngkatan
Content-Type: application/json

{
    "id_prodi": 8,
    "id_ketangkatan": 0
}